application: golangtw
version: 1
runtime: go
api_version: 2

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: _go_app
